#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'leds_comp_0', class 'leds_comp'
 * The macros are prefixed with 'LEDS_COMP_0_'.
 * The prefix is the slave descriptor.
 */
#define LEDS_COMP_0_COMPONENT_TYPE leds_comp
#define LEDS_COMP_0_COMPONENT_NAME leds_comp_0
#define LEDS_COMP_0_BASE 0x0
#define LEDS_COMP_0_SPAN 4
#define LEDS_COMP_0_END 0x3


#endif /* _ALTERA_HPS_0_H_ */
